name: basic yaml

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt flake8 pytest
        
    - name: Lint with flake8
      run: |
        flake8 .
        
    - name: Run tests
      run: |
        pytest test_main.py --maxfail=1 --disable-warnings -q
 
    - name: Run script
      run: python main.py

